import type { SurveyInstrument } from "@/lib/survey/surveyTypes";

const EXCLUSIVE = "We’d rather manage all this ourselves";

export const businessInstrument: SurveyInstrument = {
  key: "business",
  label: "Business",
  accent: "#1570ef",
  accentWash: "rgba(21,112,239,.18)",
  chip: "Closed pilot",
  steps: [
    {
      id: "role",
      theme: "behaviour",
      step: "Your role",
      type: "multi",
      ack: (name) => (name ? `First things first, ${name}.` : "First things first."),
      q: "What’s your role there?",
      hint: "Pick any that apply.",
      opts: [
        "Founder or CEO",
        "CFO or Finance Director",
        "Finance Manager or Controller",
        "Other decision-maker",
      ],
    },
    {
      id: "q1_handling",
      theme: "behaviour",
      step: "How the business runs money",
      type: "multi",
      ack: "Good.",
      q: "How does your business mostly handle money today?",
      hint: "Tap any that fit.",
      opts: [
        "Getting paid by customers",
        "Holding or saving balances",
        "Paying suppliers",
        "Moving money across borders",
        "Nothing formal yet",
      ],
    },
    {
      id: "q2_value",
      theme: "value",
      step: "What matters most",
      type: "multi",
      ack: (name) => (name ? `This one tells us the most, ${name}.` : "This one tells us the most."),
      q: "For your business right now, what matters most?",
      hint: "Pick any that apply.",
      opts: [
        "Getting paid easily — including dollars or stablecoins",
        "Protecting balances from losing value",
        "Moving money cheaply and fast, locally or abroad",
        "Full control of our own treasury",
      ],
    },
    {
      id: "q3_custody",
      theme: "comprehension / comfort",
      step: "How that sits with you",
      type: "multi",
      q: "With ENTA, only your company can move your treasury — no one can freeze it or reverse it. How does that sit with you?",
      hint: "You can feel more than one of these at once.",
      opts: [
        "A real advantage",
        "Good, but we’d need a clear recovery plan",
        "Not sure we fully get it",
        "It makes us nervous",
      ],
      more: {
        ack: (name) => (name ? `Thanks, ${name} — that’s useful.` : "Thanks — that’s useful."),
        q: "Anything your finance team would want to add on that?",
        hint: "Completely optional. Skip it and we’ll move on.",
      },
    },
    {
      id: "q4_intel",
      theme: "intelligence / enabler",
      step: "What would actually help",
      type: "multi",
      ack: (name) => (name ? `Nearly there, ${name}.` : "Nearly there."),
      dynamic: true,
      hint: "Pick as many as feel right.",
      opts: [
        "Watch rates and flag a good time to move",
        "Alert us when a rate moves in our favour",
        "Tell us when a rate beats last time",
        "Flag risks before they cost us",
        "Quietly protect our balances’ value",
        EXCLUSIVE,
      ],
      exclusive: EXCLUSIVE,
    },
    {
      id: "q5_trust",
      theme: "trust",
      step: "What would hold you back",
      type: "multi",
      q: "What would make your business hesitate to move treasury away from a traditional bank?",
      opts: [
        "Getting funds back if something goes wrong",
        "Regulatory standing we can verify",
        "A full audit trail",
        "Who we’d call if something breaks",
        "Nothing major",
      ],
    },
    {
      id: "q6_cost",
      theme: "pain → pay-intent",
      step: "What it has cost the business",
      type: "multi",
      ack: (name) => (name ? `Last real question, ${name}.` : "Last real question."),
      q: "Over the past year, which of these has cost your business — money, time, or trust?",
      opts: [
        "Balances losing value to the currency",
        "Hard or costly to get paid / hold value locally",
        "A transfer abroad slow, costly or stuck",
        "Having to convert or liquidate for cash",
        "Couldn’t control or access our funds",
        "None, really",
      ],
      more: {
        ack: "This is the bit our team reads out loud to each other.",
        q: "If one of those stands out, what happened?",
        hint: "Optional — a couple of lines is plenty.",
      },
    },
    {
      id: "ready",
      theme: "qualify",
      step: "The pilot",
      type: "single",
      ack: "Two quick ones and we’re done.",
      q: "If your business is selected for early access before public launch, would you be ready to run real transactions through ENTA?",
      opts: ["Ready now", "A small pilot first", "Not yet — we’d observe first"],
    },
    {
      id: "timing",
      theme: "qualify",
      step: "The pilot",
      type: "single",
      q: "And how soon are you looking to get started?",
      opts: ["This month", "This quarter", "Just exploring for now"],
    },
  ],
  intelligenceLead: () =>
    "Our intelligence tracks what you’d normally monitor manually — you always have the final say. Whether you’re managing currency mismatches, tracking rate shifts, or comparing payment costs, it keeps you ahead. Which of these features would help you most?",
  payIntent: {
    "Balances losing value to the currency": "preservation",
    "Hard or costly to get paid / hold value locally": "local collections + stablecoin acceptance",
    "A transfer abroad slow, costly or stuck": "cross-border settlement",
    "Having to convert or liquidate for cash": "lending",
    "Couldn’t control or access our funds": "company-controlled custody",
  },
  close: (name) =>
    `That’s everything${name ? `, ${name}` : ""} — thank you. You’re on the list, and if your business is a fit for the pilot we’ll be in touch before public launch.`,
};
